//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TspCadPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TspCadPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;-126.8070;-216.5138
        ///B;-139.2916;-173.6660
        ///C;-122.2868;-173.6660
        ///D;-122.2868;-260.1541
        ///E;46.5879;-308.3579
        ///F;46.5879;-394.8460
        ///G;-139.2916;-260.1541
        ///H;-125.5658;-187.8454
        ///I;114.7559;-340.3880
        ///J;485.8156;-95.8123
        ///K;101.0301;-326.2086
        ///L;101.0301;-412.6967
        ///M;485.8156;-182.3004
        ///N;468.8108;-182.3004
        ///O;482.5366;-109.9917
        ///P;481.2954;-138.6601
        ///Q;468.8108;-95.8123
        ///R;831.2387;-25.5598
        ///S;812.2525;-15.0544
        ///T;831.2387;-15.0544
        ///U;823.7064;-25.5598
        ///V;908.9750;-5.3682
        ///W;846.0994;-5.3682
        ///X;882.6604;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_1000nodes {
            get {
                return ResourceManager.GetString("samplegraph_1000nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;269.5896;22.4178
        ///B;199.1817;-0.8750
        ///C;269.5896;-0.8750
        ///D;249.3622;56.9447
        ///E;253.8823;13.3044
        ///F;199.1817;85.6131
        ///G;265.0694;42.7653
        ///H;161.4858;71.4337
        ///I;227.3736;28.5859
        ///J;161.4858;-15.0544
        ///K;183.4745;71.4337
        ///L;249.3622;28.5859
        ///M;183.4745;-15.0544
        ///N;216.1865;-0.8750
        ///O;161.4858;99.7924
        ///P;211.6663;42.7653
        ///Q;145.7786;85.6131
        ///R;216.1865;85.6131
        ///S;145.7786;-0.8750
        ///T;227.3736;56.9447
        ///U;183.4745;99.7924
        ///V;183.4745;13.3044
        ///W;161.4858;13.3044
        ///X;231.8937;99.7924
        ///Y;231.8937;13.3044
        ///Z;239.2221 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_100nodes {
            get {
                return ResourceManager.GetString("samplegraph_100nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0;0
        ///B;77.5844;-23.6782
        ///C;85.1167;-23.6782
        ///D;81.2503;-14.1751
        ///E;15.7072;-24.6848
        ///F;-3.279;-14.1794
        ///G;8.1749;-24.6848
        ///H;26.8098;-35.0547
        ///I;23.0356;-4.4932
        ///J;30.5679;-4.4932
        ///.
        /// </summary>
        internal static string samplegraph_10nodes {
            get {
                return ResourceManager.GetString("samplegraph_10nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0;0
        ///B;15.7072;-14.1794
        ///C;37.6959;-14.1794
        ///D;67.1289;-14.1794
        ///E;77.5844;-23.6782
        ///F;85.1167;-23.6782
        ///G;81.2503;-14.1751
        ///I;15.7072;-24.6848
        ///J;-3.279;-14.1794
        ///K;8.1749;-24.6848
        ///L;26.8098;-35.0547
        ///M;34.3421;-35.0547
        ///N;23.0356;-4.4932
        ///O;30.5679;-4.4932
        ///P;26.7015;5.0099
        ///.
        /// </summary>
        internal static string samplegraph_15nodes {
            get {
                return ResourceManager.GetString("samplegraph_15nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;15.7072;-188.7402
        ///B;15.7072;-102.2522
        ///C;8.1749;-188.7402
        ///D;67.1289;-91.7467
        ///E;-3.2790;-178.2348
        ///F;-3.2790;-91.7467
        ///G;26.7015;-159.0455
        ///H;97.1094;-72.5574
        ///I;26.7015;-72.5574
        ///J;92.5893;-115.4052
        ///K;8.1749;-102.2522
        ///L;97.1094;-159.0455
        ///M;100.9758;-168.5486
        ///N;26.8098;-112.6220
        ///O;100.9758;-82.0606
        ///P;34.3421;-112.6220
        ///Q;34.3421;-199.1101
        ///R;26.8098;-199.1101
        ///S;30.5679;-168.5486
        ///T;23.0356;-168.5486
        ///U;67.1289;-178.2348
        ///V;23.0356;-82.0606
        ///W;30.5679;-82.0606
        ///X;93.4435;-82.0606
        ///Y;93.4435;-168.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_200nodes {
            get {
                return ResourceManager.GetString("samplegraph_200nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0;0
        ///B;15.7072;-14.1794
        ///C;37.6959;-14.1794
        ///D;67.1289;-14.1794
        ///E;77.5844;-23.6782
        ///F;85.1167;-23.6782
        ///G;81.2503;-14.1751
        ///I;15.7072;-24.6848
        ///J;-3.279;-14.1794
        ///K;8.1749;-24.6848
        ///L;26.8098;-35.0547
        ///M;34.3421;-35.0547
        ///N;23.0356;-4.4932
        ///O;30.5679;-4.4932
        ///P;26.7015;5.0099
        ///Q;15.7072;14.1794
        ///R;37.6959;14.1794
        ///S;53.4031;0
        ///T;70.4079;0
        ///U;86.1151;14.1794
        ///.
        /// </summary>
        internal static string samplegraph_20nodes {
            get {
                return ResourceManager.GetString("samplegraph_20nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0;0
        ///B;70.4079;0
        ///C;65.8877;43.6403
        ///D;15.7072;14.1794
        ///E;86.1151;14.1794
        ///F;81.595;57.8197
        ///G;37.6959;14.1794
        ///H;108.1037;14.1794
        ///I;103.5836;57.8197
        ///J;53.4031;0
        ///K;123.811;0
        ///L;119.2908;43.6403
        ///M;103.5836;29.4609
        ///N;81.595;29.4609
        ///O;26.7015;5.0099
        ///P;97.1094;5.0099
        ///Q;92.5893;48.6502
        ///R;8.1749;-24.6848
        ///S;15.7072;-24.6848
        ///T;-3.279;-14.1794
        ///U;67.1289;-14.1794
        ///V;23.0356;-4.4932
        ///.
        /// </summary>
        internal static string samplegraph_22nodes {
            get {
                return ResourceManager.GetString("samplegraph_22nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0;0
        ///B;70.4079;0
        ///C;65.8877;43.6403
        ///D;15.7072;14.1794
        ///E;86.1151;14.1794
        ///F;81.595;57.8197
        ///G;37.6959;14.1794
        ///H;108.1037;14.1794
        ///I;103.5836;57.8197
        ///J;53.4031;0
        ///K;123.811;0
        ///L;119.2908;43.6403
        ///M;103.5836;29.4609
        ///N;81.595;29.4609
        ///O;26.7015;5.0099
        ///P;97.1094;5.0099
        ///Q;92.5893;48.6502
        ///R;8.1749;-24.6848
        ///S;15.7072;-24.6848
        ///T;-3.279;-14.1794
        ///U;67.1289;-14.1794
        ///V;23.0356;-4.4932
        ///W;35.4658;-18.9187
        ///.
        /// </summary>
        internal static string samplegraph_23nodes {
            get {
                return ResourceManager.GetString("samplegraph_23nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0;0
        ///B;70.4079;0
        ///C;65.8877;43.6403
        ///D;15.7072;14.1794
        ///E;86.1151;14.1794
        ///F;81.595;57.8197
        ///G;37.6959;14.1794
        ///H;108.1037;14.1794
        ///I;103.5836;57.8197
        ///J;53.4031;0
        ///K;123.811;0
        ///L;119.2908;43.6403
        ///M;103.5836;29.4609
        ///N;81.595;29.4609
        ///O;26.7015;5.0099
        ///P;97.1094;5.0099
        ///Q;92.5893;48.6502
        ///R;8.1749;-24.6848
        ///S;15.7072;-24.6848
        ///T;-3.279;-14.1794
        ///U;67.1289;-14.1794
        ///V;23.0356;-4.4932
        ///W;35.4658;-18.9187
        ///X;47.23;-18.9187
        ///.
        /// </summary>
        internal static string samplegraph_24nodes {
            get {
                return ResourceManager.GetString("samplegraph_24nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0.0000;0.0000
        ///B;70.4079;0.0000
        ///C;65.8877;43.6403
        ///D;15.7072;14.1794
        ///E;86.1151;14.1794
        ///F;81.5950;57.8197
        ///G;37.6959;14.1794
        ///H;108.1037;14.1794
        ///I;53.4031;0.0000
        ///J;123.8110;0.0000
        ///K;37.6959;-14.1794
        ///L;15.7072;-14.1794
        ///M;81.5950;29.4609
        ///N;26.7015;5.0099
        ///O;97.1094;5.0099
        ///P;8.1749;-24.6848
        ///Q;15.7072;-24.6848
        ///R;-3.2790;-14.1794
        ///S;67.1289;-14.1794
        ///T;23.0356;-4.4932
        ///U;93.4435;-4.4932
        ///V;30.5679;-4.4932
        ///W;100.9758;-4.4932
        ///X;26.8098;-35.0547
        ///Y;34.3421;-35.0547
        ///.
        /// </summary>
        internal static string samplegraph_25nodes {
            get {
                return ResourceManager.GetString("samplegraph_25nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;180.1207;-199.1101
        ///B;0;244.06
        ///C;172.5884;-199.1101
        ///D;180.1207;-112.622
        ///E;65.8877;201.2122
        ///F;15.7072;258.2393
        ///G;0;157.5719
        ///H;70.4079;244.06
        ///I;70.4079;157.5719
        ///J;239.2221;-82.0606
        ///K;239.2221;-168.5486
        ///L;212.9075;-178.2348
        ///M;168.8142;-82.0606
        ///N;168.8142;-168.5486
        ///O;246.7544;-82.0606
        ///P;246.7544;-168.5486
        ///Q;172.5884;-112.622
        ///R;176.3465;-82.0606
        ///S;176.3465;-168.5486
        ///T;119.2908;201.2122
        ///U;37.6959;229.8806
        ///V;53.4031;157.5719
        ///W;123.811;180.8647
        ///X;123.811;157.5719
        ///Y;15.7072;229.8806
        ///Z;15.70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_300nodes {
            get {
                return ResourceManager.GetString("samplegraph_300nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0.0000;0.0000
        ///B;70.4079;0.0000
        ///C;65.8877;43.6403
        ///D;15.7072;14.1794
        ///E;86.1151;14.1794
        ///F;81.5950;57.8197
        ///G;37.6959;14.1794
        ///H;108.1037;14.1794
        ///I;103.5836;57.8197
        ///J;53.4031;0.0000
        ///K;123.8110;0.0000
        ///L;123.8110;23.2928
        ///M;119.2908;43.6403
        ///N;37.6959;-14.1794
        ///O;103.5836;29.4609
        ///P;15.7072;-14.1794
        ///Q;81.5950;29.4609
        ///R;26.7015;5.0099
        ///S;97.1094;5.0099
        ///T;92.5893;48.6502
        ///U;8.1749;-24.6848
        ///V;15.7072;-24.6848
        ///W;-3.2790;-14.1794
        ///X;67.1289;-14.1794
        ///Y;23.0356;-4.4932
        ///Z;93.4435;-4.4932
        ///A1;30.5679;-4. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_30nodes {
            get {
                return ResourceManager.GetString("samplegraph_30nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;-126.8070;-216.5138
        ///B;-139.2916;-173.6660
        ///C;-122.2868;-173.6660
        ///D;-122.2868;-260.1541
        ///E;46.5879;-308.3579
        ///F;46.5879;-394.8460
        ///G;-139.2916;-260.1541
        ///H;-125.5658;-187.8454
        ///I;114.7559;-340.3880
        ///J;485.8156;-95.8123
        ///K;101.0301;-326.2086
        ///L;101.0301;-412.6967
        ///M;485.8156;-182.3004
        ///N;468.8108;-182.3004
        ///O;482.5366;-109.9917
        ///P;481.2954;-138.6601
        ///Q;468.8108;-95.8123
        ///R;831.2387;-25.5598
        ///S;812.2525;-15.0544
        ///T;831.2387;-15.0544
        ///U;823.7064;-25.5598
        ///V;908.9750;-5.3682
        ///W;846.0994;-5.3682
        ///X;882.6604;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_500nodes {
            get {
                return ResourceManager.GetString("samplegraph_500nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;0.0000;86.4881
        ///B;0.0000;0.0000
        ///C;70.4079;86.4881
        ///D;70.4079;0.0000
        ///E;65.8877;43.6403
        ///F;15.7072;100.6674
        ///G;15.7072;14.1794
        ///H;86.1151;100.6674
        ///I;86.1151;14.1794
        ///J;81.5950;57.8197
        ///K;37.6959;100.6674
        ///L;37.6959;14.1794
        ///M;108.1037;14.1794
        ///N;103.5836;57.8197
        ///O;53.4031;86.4881
        ///P;53.4031;0.0000
        ///Q;123.8110;23.2928
        ///R;123.8110;0.0000
        ///S;119.2908;43.6403
        ///T;37.6959;72.3087
        ///U;37.6959;-14.1794
        ///V;103.5836;29.4609
        ///W;15.7072;72.3087
        ///X;15.7072;-14.1794
        ///Y;81.5950;29.4609
        ///Z;26.7015;91.4980
        ///A1;26.7015;5. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samplegraph_50nodes {
            get {
                return ResourceManager.GetString("samplegraph_50nodes", resourceCulture);
            }
        }
    }
}
